name             'achiiibot'
maintainer       'okuramasafumi'
maintainer_email 'masafumi@achiiive.com'
license          'All rights reserved'
description      'Installs/Configures achiiibot'
long_description 'Installs/Configures achiiibot'
version          '0.2.0'

depends 'git'
depends 'nodejs'
depends 'node'
depends 'redis'
depends 'deploy_key'
depends 'monit', '>= 1.0.0'
depends 'ssh'
